### ISSUE TITLE
Доделать тестовое задание

### ISSUE THREAD

**Issue by Kasiwadzaki** [NevostruevaYana/BICProject#1]
Привет! Меня зовут Вадим, я разработчик компании BaltInfoCom.
Посмотрел твой код и есть пара моментов которые надо исправить:
 - В тестовом надо не просто выводить в терминал результат, но и записывать в новый файл получившееся(Об этом написано в тестовом задании)
 - Не очень хорошо писать код выстраивая методы в определенном порядке, то есть если ты явно не выстраиваешь зависимость от одного метода к другому посредством передачи аргументов, то просто поменяв порядок вызова метода программа перестанет работать
 - Нет обработки ошибок, что будет если в аргументы придет не путь к файлу, а любая другая строка или ее вообще не будет
 - printStackTrace по хорошему не использовать, а выбрасывать понятное исключение
 - Так же запусти вот этот файл после всех правок на своем коде и скажи сколько у тебя получилось и за какое время https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z
 - Добавить тесты на код, пара юнит тестов и один интеграционный. Использовать библиотеку junit 5

**Comment by Kasiwadzaki** [comment]
@NevostruevaYana Ваш код выдает ответ "0 групп" на файл который я скидывал выше, нужно исправить. Когда поправите отпишитесь пожалуйста в этом треде сколько у вас групп получилось и за какое время после правок.

**Comment by alexkoss** [comment]
@NevostruevaYana Яна, вы закончили задание? Удалось получить количество и время получения?

**Comment by NevostruevaYana** [comment]
@alexkoss @Kasiwadzaki 
Поправила немного тесты.
Сейчас закончила.
Хотела прикрутить бенчмарки для average time но уже немного не успеваю.
Запустила с аргументом lng-big.csv, получила 6197 групп. Запускала несколько раз, в среднем получила время 25 +- 3 сек

**Comment by alexkoss** [comment]
@NevostruevaYana Ответ некорректный. Попробуете ещё одну итерацию доработок?

**Comment by NevostruevaYana** [comment]
Да, попробую

**Comment by NevostruevaYana** [comment]
Count of groups: 104459

**Comment by NevostruevaYana** [comment]
@alexkoss

**Comment by alexkoss** [comment]
Ответ некорректный. Попробуете ещё итерацию?

**Comment by NevostruevaYana** [comment]
Конечно)

**Comment by alexkoss** [comment]
@NevostruevaYana Спасибо за уделённое время.
